### ISSUE TITLE
遇到invalid syntax

### ISSUE THREAD

**Issue by Lordores** [Redcxx/Pikax#8]
具体情况
`E:\style\Pikax>python demo.py
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    from pikax import Pikax, settings, params
  File "E:\style\Pikax\pikax\__init__.py", line 3, in <module>
    from .api import *
  File "E:\style\Pikax\pikax\api\__init__.py", line 2, in <module>
    from . import androidclient
  File "E:\style\Pikax\pikax\api\androidclient.py", line 105
    self._headers.update({'Authorization': f'{self._token_type.title()} {self._access_token}'})
                                                                                            
SyntaxError: invalid syntax`

这个`self._headers.update({'Authorization': f'{self._token_type.title()} {self._access_token}'})`里的冒号是跟在Authorization后面的还是？

**Comment by Redcxx** [comment]
你好~@Lordores 我目前是Python 3.8.3, 不过看起来是f-string的问题, Python 3.6以上就能解决这个问题。

**Comment by Lordores** [comment]
的确是python的版本问题，感谢

**Comment by Redcxx** [comment]
不客气~
